// auto generated - do not edit

	{ "requests", 'q', & net_stats.n_requests },
	{ "tcp", 'q', & net_stats.n_tcp },
	{ "drop", 'q', & net_stats.n_drop },
	{ "edns", 'q', & net_stats.n_edns },
	{ "client_subnet_ipv4", 'q', & net_stats.n_client_subnet_ipv4 },
	{ "client_subnet_ipv6", 'q', & net_stats.n_client_subnet_ipv6 },
	{ "rcode0", 'q', & net_stats.n_rcode[0] },
	{ "rcode1", 'q', & net_stats.n_rcode[1] },
	{ "rcode2", 'q', & net_stats.n_rcode[2] },
	{ "rcode3", 'q', & net_stats.n_rcode[3] },
	{ "rcode4", 'q', & net_stats.n_rcode[4] },
	{ "rcode5", 'q', & net_stats.n_rcode[5] },
	{ "rcode6", 'q', & net_stats.n_rcode[6] },
	{ "rcode7", 'q', & net_stats.n_rcode[7] },
	{ "glb", 'q', & net_stats.n_glb },
	{ "glb_nolocation", 'q', & net_stats.n_glb_nolocation },
	{ "glb_failover", 'q', & net_stats.n_glb_failover },
	{ "glb_failover_fail", 'q', & net_stats.n_glb_failover_fail },
